name: Codex CI

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  codex-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm
  
      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint || exit 1

      - name: Build app
        run: pnpm run build || exit 1

      - name: Run tests
        run: pnpm run test || echo "No tests defined"
