name: Codex CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  codex-refactor:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      VERCEL_TOKEN:     ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & Python
        uses: actions/setup-node@v4
        with: { node-version: "18" }
      - uses: actions/setup-python@v4
        with: { python-version: "3.11" }

      - name: Install deps & Vercel build
        run: |
          chmod +x ./setup-codex.sh
          ./setup-codex.sh

      - name: Full-repo analysis & patch
        run: |
          chmod +x ./codex-analyze.sh
          ./codex-analyze.sh

      - name: Commit & Push refactoring
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git push --force --set-upstream origin codex/refactor-temp

      - name: Create or update Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: codex/refactor-temp
          base: main
          title: "🤖 Codex full-repo refactoring"
          commit-message: "chore: apply Codex refactoring"
